---
# tasks file for nodejs
- name: Node.js | Get installation script
  get_url:
    url: "http://deb.nodesource.com/setup_6.x"
    dest: "{{ temp_folder }}/nodejs.sh"

- name: Node.js | Set execution right to script
  file:
    path: "{{ temp_folder }}/nodejs.sh"
    mode: "u+x"

- name: Node.js | Execute installation script
  shell: "{{ temp_folder }}/nodejs.sh"

- name: Node.js | Remove installation script
  file:
    path: "{{ temp_folder }}/nodejs.sh"
    state: absent

- name: Node.js | Install Node.js
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - build-essential
    - nodejs

- name: Node.js | Install bower and gulp globally
  npm: name={{ item }} state=present global=yes
  with_items:
    - bower
    - gulp
